version: "3.7"
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - backend    
      
  bi-api-db:
    image: bi-api-db
    expose:
      - 80
    ports:
      - "6002:80"
    networks:
      - backend    
    restart: always
  
  bi-api-ml:
    image: bi-api-ml
    expose:
      - 80
    ports:
      - "5000:80" 
    networks:
      - backend    
    restart: always

  bi-client:
    image: bi-client
    expose:
      - 80
    ports:
      - "7000:80"
    networks:
      - backend    
    restart: always

networks:
  backend:

         