version: "3.7"
services:
  bi-api-db:
    image: bi-api-db
    build:
      context: ./MinimalApi
    expose:
      - 80
      - 443
    ports:
      - "6002:80"
      - "6001:443" 
    networks:
      - backend    
    restart: always
  
  bi-api-ml:
    image: bi-api-ml
    build:
      context: ./MLModel2_WebApi1
    expose:
      - 80
      - 443
    ports:
      - "5000:80" 
      - "5001:443"
    networks:
      - backend    
    restart: always

  bi-client:
    image: bi-client
    build:
      context: ./BI_Dashboard_Webclient
    expose:
      - 80
      - 443
    ports:
      - "7000:80"
      - "7001:443" 
    networks:
      - backend    
    restart: always

networks:
  backend:

         